db:
  migration_path: internal/constant/query/schemas
  migration_path_up: internal/constant/query/schemas/up
  name: cashflow
  host: db
  port: 5432
  user: postgres
  password: secret
  url: postgresql://postgres:secret@db:5432/cashflow?sslmode=disable
test_db:
  name: cashflow
  host: localhost
  port: 5433
  user: postgres
  password: secret
  url: postgresql://postgres:secret@localhost:5433/cashflow?sslmode=disable
app:
  host: 0.0.0.0
  port: 8282
  timeout: 30s
  limit: 100
  interval: 15
rabbitmq:
  url: amqp://guest:guest@localhost:5672/
workerpool:
  max_workers: 10
  task_buffer: 1000
